# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Back Burner', 'Back Burner'), ('On Deck', 'On Deck'), ('In Process', 'In Process'), ('Complete', 'Complete')], max_length=20)),
                ('priority', models.CharField(choices=[('Glacial', 'Glacial'), ('Sloth', 'Sloth'), ('Snail', 'Snail'), ('Rabbit', 'Rabbit'), ('The Flash', 'The Flash')], max_length=15)),
            ],
        ),
    ]
